version: '3.8'

services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_DB: homework
      POSTGRES_USER: surbana
      POSTGRES_PASSWORD: 123456a@
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
